//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EZAsk
{
    using System;
    using System.Collections.Generic;
    
    public partial class Forum
    {
        public int IDPost { get; set; }
        public string TituloPost { get; set; }
        public string UsuarioPost { get; set; }
        public string Post { get; set; }
        public Nullable<int> RespostaPost { get; set; }
        public Nullable<int> Materia { get; set; }
    
        public virtual Resposta Resposta { get; set; }
        public virtual Materia Materia1 { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
