//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EZAsk
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Usuario()
        {
            this.Forum = new HashSet<Forum>();
            this.Resposta = new HashSet<Resposta>();
        }
    
        public string EmailUsuario { get; set; }
        public string NomeLogin { get; set; }
        public string NomeUsuario { get; set; }
        public string SenhaUsuario { get; set; }
        public Nullable<bool> UsuarioAtivo { get; set; }
        public Nullable<int> permissao { get; set; }
        public Nullable<int> Cidade { get; set; }
        public Nullable<int> Bairro { get; set; }
        public Nullable<int> TipoUsuario { get; set; }
        public byte[] ImgUsuario { get; set; }
        public Nullable<int> Estado { get; set; }
        public Nullable<int> Pais { get; set; }
        public string DataNascimento { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Forum> Forum { get; set; }
        public virtual Pais Pais1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Resposta> Resposta { get; set; }
        public virtual TipoUsuario TipoUsuario1 { get; set; }
        public virtual Cidade Cidade1 { get; set; }
        public virtual Estado Estado1 { get; set; }
    }
}
